sudo: false

language:
    - php
    - node_js

php:
    - 5.2
    - 5.6
    - 7.0

env:
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

matrix:
    exclude:
        - php: 5.6
          env: WP_VERSION=3.8 WP_MULTISITE=0
        - php: 5.6
          env: WP_VERSION=3.8 WP_MULTISITE=1
        - php: 7.0
          env: WP_VERSION=3.8 WP_MULTISITE=0
        - php: 7.0
          env: WP_VERSION=3.8 WP_MULTISITE=1

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

notifications:
    slack:
        secure: "e/7dqZ9RIa7piLMSw7OAUH5/CSXeBg4I0LrbBSW57rdnrwjJVZGXXSKKVvB32PhCQDhzO6JyMzZUpTSx+iBsNur/qi+edIb9JFb5WSIhdpEanKUnR/mL7ujdwzEduJql/dzcst8OffNQXK7nwQ1KqE/P0Jo1W7MMW3p136k2FYSH6S6sPfF25JoEeaIbVYb7+GZM6mQ4lJxgZf74vdVgUYIvQPFGzyabZm22FKTQtjsxBBv4M7dj7Ze5ZcK+5R3Eop/z8NbzJDxchE1zSArC3YGzQcMIsLRFrcOlmqtXIjZI8JyvQK3YBHGxgz6zjvayshahAt04D7soAYKoWg1QSsK6m+ix1XCo7T7vN91nZaAZ2HCzHnzViMEZmv9c7t9lYKBNP+ATMrmU53jNgs5tRJLYnIC9zB6uXt8SSGhFYpy6w04KpUSCHm7x3L95zMPRphQKVDX+SCk6M+eE9uCY7mFGj16jsH3WIoEjSkCWI/8vMS/67kIdD9pNsSj56ACgad8GnVunBvYFwZvMEyNOeQLgPQwUl0j5OF8IaIOR9ziHoAdNWoRcpoqwpTAuyBSkYk2sHnclrWBWbLNnwwp6/Eq3yrsNqjTMKeKREN4MwBOi6+/b9NeIqyK3HQANmf8Gv4OHOWGN60MzIi+taN68jmMg4+S/Ys0DfHESI8wLaJY="
